version: '3.8'

services:
  app:
    build: ./CommentService/CommentService.Api
    environment:
      - MONGO_USER=${COMMENT_MONGO_USER}
      - MONGO_PASSWORD=${COMMENT_MONGO_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${COMMENT_MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${COMMENT_MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${COMMENT_MONGO_DATABASE}
      - MONGO_HOST=comment_mongodb         
    ports:
      - "8008:8008"
    depends_on:
      - comment_mongodb                    
    networks:
      - microservices_shared_net

networks:
  microservices_shared_net:
    external: true   