FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY UserGameTrackingService.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

COPY --from=build /app/out .

EXPOSE 8005

ENV ASPNETCORE_URLS=http://+:8005
ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "UserGameTrackingService.dll"]
