upstream ad_service {
    server adservice;
}

server {
    listen 80;
    server_name adservice.local;

    location /ads/swagger/ {
        rewrite ^/ads/swagger/(.*)$ /swagger/$1 break;
        proxy_pass http://ad_service;
    }

    location = /ads/swagger/v1/swagger.json {
        proxy_pass http://ad_service/swagger/v1/swagger.json;
    }

    location ^~ /ads {
        proxy_pass http://ad_service;
    }
}

server {
    listen 443 ssl;
    server_name adservice.local;

    ssl_certificate     /etc/nginx/certs/localhost.crt;
    ssl_certificate_key /etc/nginx/certs/localhost.key;

    location /ads/swagger/ {
        rewrite ^/ads/swagger/(.*)$ /swagger/$1 break;
        proxy_pass http://ad_service;
    }

    location = /ads/swagger/v1/swagger.json {
        proxy_pass http://ad_service/swagger/v1/swagger.json;
    }

    location ^~ /ads {
        proxy_pass http://ad_service;
    }
}
