# DUSK-SKY-MICROSERVICES/AuthService/docker-compose.auth.yml
version: '3.8'

services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service_app_isolated 
    ports:
      - "8001:8000" 
    volumes:
      - ./app:/app/auth_service/app
    environment:
      MONGODB_URI: "mongodb://mongo_for_auth:27017/" 
      MONGODB_NAME: "auth_service_db"             

      RABBITMQ_URL: "amqp://guest:guest@host.docker.internal:5672/"
      
      PYTHONUNBUFFERED: 1
      JWT_SECRET_KEY: "${JWT_SECRET_KEY_AUTH}" 
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "${JWT_ACCESS_TOKEN_EXPIRE_MINUTES_AUTH:-30}" 
      JWT_ALGORITHM: "${JWT_ALGORITHM_AUTH:-HS256}"
    depends_on:
      - mongo_for_auth
    networks:
      - auth_internal_net

  mongo_for_auth:
    image: mongo:latest
    container_name: mongo_for_auth_container_isolated 
    ports:
      - "27017:27017" 
    volumes:
      - mongo_auth_data:/data/db 
    networks:
      - auth_internal_net

volumes:
  mongo_auth_data:

networks:
  auth_internal_net:
    driver: bridge