name: Test Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # ---- AuthService ----
      - name: Install AuthService dependencies
        run: |
          cd AuthService
          pip install -r requirements.txt

      - name: Run AuthService tests
        run: |
          cd AuthService
          pytest

      # ---- UserService ----
      - name: Install UserService dependencies
        run: |
          cd UserService
          pip install -r requirements.txt

      - name: Run UserService tests
        run: |
          cd UserService
          pytest

      # ---- ReviewService ----
      - name: Install ReviewService dependencies
        run: |
          cd ReviewService
          pip install -r requirements.txt

      - name: Run ReviewService tests
        run: |
          cd ReviewService
          pytest

      # ---- FriendshipService ----
      - name: Install FriendshipService dependencies
        run: |
          cd FriendshipService
          pip install -r requirements.txt

      - name: Run FriendshipService tests
        run: |
          cd FriendshipService
          pytest
